/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sadcup_android_jnionas_JNIKit */

#ifndef _Included_sadcup_android_jnionas_JNIKit
#define _Included_sadcup_android_jnionas_JNIKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sadcup_android_jnionas_JNIKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sadcup_android_jnionas_JNIKit_square
  (JNIEnv *, jclass, jint);

/*
 * Class:     sadcup_android_jnionas_JNIKit
 * Method:    welcome
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sadcup_android_jnionas_JNIKit_welcome
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
